# Generated by Django 4.1.1 on 2022-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.CharField(help_text='日期', max_length=70, verbose_name='日期')),
                ('regMember', models.CharField(help_text='注册人数', max_length=70, verbose_name='注册人数')),
                ('toDayActivity', models.CharField(help_text='总日活', max_length=70, verbose_name='总日活')),
                ('memberToDayActivity', models.CharField(help_text='会员日活', max_length=70, verbose_name='会员日活')),
                ('memberQuantityPaid', models.CharField(help_text='会员付费人数', max_length=70, verbose_name='会员付费人数')),
                ('totalMemberPayments', models.CharField(help_text='会员付费金额', max_length=70, verbose_name='会员付费金额')),
                ('candyPaymentQuantity', models.CharField(help_text='糖果付费人数', max_length=70, verbose_name='糖果付费人数')),
                ('totalCandyPayment', models.CharField(help_text='糖果付费金额', max_length=70, verbose_name='糖果付费金额')),
                ('memberConversionRate', models.CharField(blank=True, help_text='会员转化率', max_length=70, null=True, verbose_name='会员转化率')),
                ('candyConversion', models.CharField(blank=True, help_text='糖果转化率', max_length=70, null=True, verbose_name='糖果转化率')),
            ],
            options={
                'verbose_name': '概况统计',
                'verbose_name_plural': '概况统计',
            },
        ),
    ]
