# Generated by Django 4.1.1 on 2022-09-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberAdd', models.CharField(help_text='新增用户', max_length=70, verbose_name='新增用户')),
                ('activeUsers', models.CharField(help_text='活跃用户', max_length=70, verbose_name='活跃用户')),
                ('quantityPaid', models.CharField(help_text='充值人数', max_length=70, verbose_name='充值人数')),
                ('totalRecharge', models.CharField(help_text='充值金额', max_length=70, verbose_name='充值金额')),
            ],
            options={
                'verbose_name': '概况',
                'verbose_name_plural': '概况',
            },
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': '详细统计', 'verbose_name_plural': '详细统计'},
        ),
    ]
